# Generated by Django 3.2.5 on 2021-07-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='アーティスト名')),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='曲名')),
                ('category', models.CharField(choices=[('K-POP', 'K-POP'), ('J-POP', 'J-POP'), ('ELSE', 'その他')], max_length=31)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.artist', verbose_name='アーティスト')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='タイトル')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('language', models.CharField(choices=[('Japanese', '日本語'), ('English', '英語'), ('Korean', '韓国語'), ('Chinese', '中国語')], max_length=31)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.song', verbose_name='曲')),
            ],
            options={
                'db_table': 'lyrics',
            },
        ),
    ]
