# Generated by Django 3.2.5 on 2021-07-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0004_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='movie_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='動画URL'),
        ),
    ]
